### ISSUE TITLE
Require lowercase hex hashes?

### ISSUE THREAD

**Issue by wking** [docker/go-digest#3]
This repo currently [allows case-insensitive hex][1], but opencontainers/image-spec#292 argued for lowercase hex to:

* Make comparison easier
* Make it easier to serve blobs out of a case-insensitive filesystem store.
* Avoid having two otherwise-identical descriptor (or descriptor-containing) blobs with different hashes because they picked different hex-casing.

Do we want to adjust `DigestRegexp` to make it compatible with the current image-spec requirements?  Or are there good reasons to allow mixed-case hex, in which case, should image-spec be adjusted to allow them again?

[1]: https://github.com/docker/go-digest/blob/36db1987e6cbe3a984cf32f68f524abb6964d716/digest.go#L48

**Comment by stevvooe** [comment]
This maintains the possibility for future support of case-sensitive types, such as those that encode the binary portion as base64, over hex.
