### ISSUE TITLE
Document Signed-off-by

### ISSUE THREAD

**Issue by wking** [docker/go-digest#5]
I added one in #4, but grepping for `Signed-off-by` in this repo didn't give any hits.  We probably want to land some boilerplate docs around it before this repo gets too far along.

**Comment by stevvooe** [comment]
@wking Could you PR the CONTRIBUTING.md from https://github.com/docker/opensource/blob/master/project-template/CONTRIBUTING.md for me?

I am updating the deps in distribution and docker.
